// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonId } from './Person';

/** Identifier type for public.account */
export type AccountId = string & { __brand: 'AccountId' };

/** Represents the table public.account */
export default interface Account {
  id: AccountId;

  person_id: PersonId;

  username: string;

  password: string;
}

/** Represents the initializer for the table public.account */
export interface AccountInitializer {
  /** Default value: nextval('account_id_seq'::regclass) */
  id?: AccountId;

  person_id: PersonId;

  username: string;

  password: string;
}

/** Represents the mutator for the table public.account */
export interface AccountMutator {
  id?: AccountId;

  person_id?: PersonId;

  username?: string;

  password?: string;
}
