// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.person */
export type PersonId = string & { __brand: "PersonId" };

/** Represents the table public.person */
export default interface Person {
  id: PersonId;
}

/** Represents the initializer for the table public.person */
export interface PersonInitializer {
  /** Default value: nextval('users_id_seq'::regclass) */
  id?: PersonId;
}

/** Represents the mutator for the table public.person */
export interface PersonMutator {
  id?: PersonId;
}
