// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PersonId } from './Person.ts';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.session */
export default interface Session {
  id: SessionId;

  person_id: PersonId;
}

/** Represents the initializer for the table public.session */
export interface SessionInitializer {
  /** Default value: nextval('session_id_seq'::regclass) */
  id?: SessionId;

  person_id: PersonId;
}

/** Represents the mutator for the table public.session */
export interface SessionMutator {
  id?: SessionId;

  person_id?: PersonId;
}
